{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName | default (printf "%s-secrets" (include "gestao-de-notas.fullname" .)) }}
  labels:
    {{- include "gestao-de-notas.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}

