{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "auth.fullname" . }}-secrets
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecrets.data }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.sealedSecrets.secretName | default (printf "%s-secrets" (include "auth.fullname" .)) }}
      labels:
        {{- include "auth.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
